name: azure
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - azure-core
  - azure-ai-documentintelligence
  - cython
  - flask
  - python
  - python-dotenv
  - regex
  - setuptools
  - waitress
  # Dev dependencies
  - djlint
  - ipykernel
  - ruff
